[package]
name = "nothing"
version = "0.1.0"
description = "An application that intentionally does almost nothing."
authors = ["Jake Castillo"]
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
